# OPS Center Analyzer Adapter Configuration
# InfluxDB Settings
influxdb_url=http://10.97.238.41:8086
influxdb_token=MwAPhawu0nykJgzzO3t2iDMa0NPadmrGuE2S5nyr_WeKpXvYrdUtQPef79VRUUFTYHmMCseZMvGvN5r6SzXDkQ==
influxdb_org=Turkcell
influxdb_bucket=Turkcell_python
# OPS Center Settings
ops_center_url=http://localhost:24221
ops_center_user=admin
ops_center_password=Opscenter123
# Collection Settings (in minutes)
collection_interval=5
collection_offset=5