# OPS Center Analyzer Adapter Configuration
# InfluxDB Settings
influxdb_url=http://10.97.238.41:8086
influxdb_token=MhrtGII7B7oxdw23zTC6hoInaRvsWvptA4sYFfP15p5zshG89bScXPdx1voA1OE6WyjbZB9fUczHn0GyU26l3A==
influxdb_org=Turkcell
influxdb_bucket=Turkcell_Test2
# OPS Center Settings
ops_center_url=http://localhost:24221
ops_center_user=admin
ops_center_password=Opscenter123
# Collection Settings (in minutes)
collection_interval=5
collection_offset=5