#!/bin/bash -eu

#
# SCI. All Rights Reserved. Copyright (C) 2024, Hitachi Vantara, Ltd.
#

source "$(dirname $(readlink -f $0))/.internal/paths"
source "${MESSAGES_DEF}"
source "${CRON_CONF_KEYS}"
readonly ETL_COLLECTION_INTERVAL_SPECIFIABLE_VALUES_DEF="${SBIN_DIR}/validate-etl-collection-interval"
readonly ETL_COLLECTION_ENABLED_SPECIFIABLE_VALUES_DEF="${SBIN_DIR}/validate-etl-collection-enabled"
source "${ETL_COLLECTION_INTERVAL_SPECIFIABLE_VALUES_DEF}"
source "${ETL_COLLECTION_ENABLED_SPECIFIABLE_VALUES_DEF}"
readonly TMP_CRON_CONF=$(mktemp "/tmp/${0##*/}.tmp.XXXXXX")
readonly ETL_SLEEP_TIME_IN_SEC=30

### validate user config
function validate_user_cron_config(){
  ##### check for collection interval and validate
  if [ ! -v "${ETL_COLLECTION_INTERVAL_IN_MINUTES_KEY}" ]; then
    echo "$(printf "${KNAQ60403E}" "${ETL_COLLECTION_INTERVAL_IN_MINUTES_KEY}")"
    exit 1
  fi
  validate_collection_interval "${!ETL_COLLECTION_INTERVAL_IN_MINUTES_KEY}"

  ##### check for etl collection enabled and validate
  if [ ! -v "${ETL_COLLECTION_ENABLED_KEY}" ]; then
    echo "$(printf "${KNAQ60403E}" "${ETL_COLLECTION_ENABLED_KEY}")"
    exit 1
  fi
  validate_etl_collection_enabled "${!ETL_COLLECTION_ENABLED_KEY}" "${ETL_COLLECTION_ENABLED_KEY}"
}

function resolve_cron_schedule_part() {
  local collection_interval_in_hour=$1
  local collection_interval_in_minutes=$2
  if [ "${collection_interval_in_hour}" = 0 ]; then
    schedule_minutes_part=0-59/${collection_interval_in_minutes}
    schedule_hour_part="*"
  elif [ "${collection_interval_in_hour}" = 24 ]; then
    schedule_minutes_part=15
    schedule_hour_part=0
  else
    schedule_minutes_part=0
    schedule_hour_part="0-23/${collection_interval_in_hour}"
  fi
  echo "${schedule_minutes_part} ${schedule_hour_part} * * *"
}

function create_cron_file_lines(){
  local -r collection_interval_in_hour=$(("${ETL_COLLECTION_INTERVAL_IN_MINUTES}"/60))
  local cron_file_lines=
  local cron_comment_out_agent=

  if [ "${ETL_COLLECTION_ENABLED}" = "false" ]; then
    cron_comment_out_agent="# "
  fi
  if [ "${collection_interval_in_hour}" = 0 ]; then
    ### collection interval less than 1 hour case
    cron_file_lines="${cron_file_lines}$(cat << _EOF_
${cron_comment_out_agent}0-59/${ETL_COLLECTION_INTERVAL_IN_MINUTES} * * * * root sleep ${ETL_SLEEP_TIME_IN_SEC}; ${INST_DIR}/run.sh --scheduled > /dev/null 2>&1
_EOF_
)\n"
  else
    ### collection interval is 1 hour or more case
    schedule_part=$(resolve_cron_schedule_part "${collection_interval_in_hour}" "${ETL_COLLECTION_INTERVAL_IN_MINUTES}")
    cron_file_lines="${cron_file_lines}$(cat << _EOF_
${cron_comment_out_agent}${schedule_part} root sleep ${ETL_SLEEP_TIME_IN_SEC}; ${INST_DIR}/run.sh --scheduled > /dev/null 2>&1
_EOF_
)\n"
  fi
  echo -e "${cron_file_lines}"
}

cleanup() {
  [[ -f "${TMP_CRON_CONF}" ]] && rm -f "${TMP_CRON_CONF}"
}
trap cleanup EXIT
trap 'trap EXIT; cleanup; exit 1' SIGHUP SIGINT SIGTERM

## check file exist
if [ ! -f "${USER_CRON_CONF}" ]; then
  cp -p "${DEFAULT_USER_CRON_CONF}" "${USER_CRON_CONF}"
  chown "${DAEMON_USER}":"${DAEMON_USER}" "${USER_CRON_CONF}"
fi

## validate user config
source "${USER_CRON_CONF}"

validate_user_cron_config
CRON_FILE_LINES=$(create_cron_file_lines)
cat << _EOF_ > "${TMP_CRON_CONF}"
${CRON_FILE_LINES}
_EOF_

## update cron file
if [ ! -f "${TMP_CRON_CONF}" ]; then
  echo "${KNAQ60401E}"
  exit 1
fi

cat "${TMP_CRON_CONF}" > "${CRON_FILE}"
if systemctl -q is-active crond.service; then
  systemctl reload crond.service
fi
