#!/bin/bash -eu
readonly COLLECTION_INTERVAL_SPECIFIABLE_VALUES=(1 5 10 15 20 30 60 120 180 240 360 480 720 1440)

function validate_collection_interval() {
  if [ "$1" = "" ]; then
    echo "$(printf "${INVALID_VALUE_ERR_MSG}" "minutes")"
    exit 1
  fi
  local _collection_interval=$1
  for _num in ${COLLECTION_INTERVAL_SPECIFIABLE_VALUES[@]}
  do
    if [ ${_collection_interval} = ${_num} ]; then
      return 0
    fi
  done
  echo "$(printf "${INVALID_VALUE_ERR_MSG}" "minutes")"
  exit 1
}
